/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:aa44042b-c800-473b-9391-dd170db9a1be",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_wbgDwobhx",
    "aws_user_pools_web_client_id": "5a398ji0ouq13bcd51v5sn7b51",
    "oauth": {},
    "aws_content_delivery_bucket": "ngcognito-20200622183301-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://ngcognito-20200622183301-hostingbucket-dev.s3-website-us-east-1.amazonaws.com",
    "aws_appsync_graphqlEndpoint": "https://yew3jckepjej3ai35mhgu52ht4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-n3g7tbczybh6pm2mlikpvbqv5u"
};


export default awsmobile;
